version: "3.3"

name: flops_management

services:

  flops_manager:
    image: flops_manager
    build: ../flops_manager_package/ 
    hostname: flops_manager
    container_name: flops_manager
    environment:
      - FLOPS_MANAGER_PORT=5072
      - FLOPS_IMAGE_REGISTRY_PORT=5073
      - SYSTEM_MANAGER_IP=system_manager
      - SYSTEM_MANAGER_PORT=10000
      - FLOPS_MQTT_BROKER_PORT=9027
      - FLOPS_MQTT_BROKER_URL=flops_mqtt
      - FLOPS_DB_PORT=10027
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "5072"
    ports:
      - "5072:5072"
    networks:
      - root_orchestrator_default
  
  flops_image_registry:
    image: image_registry
    build: image_registry/
    container_name: flops_image_registry
    volumes:
      - registry_data:/var/lib/registry
    expose:
      - "5073"
    ports:
      - "5073:5073"
    networks:
      - root_orchestrator_default

  flops_mqtt:
    image: eclipse-mosquitto:2
    hostname: flops_mqtt
    container_name: flops_mqtt
    restart: unless-stopped
    ports:
      - "9027:9027"
    volumes:
      - ../flops_manager_package/flops_manager/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mosquitto/data
      - /mosquitto/log

  flops_db:
    image: mongo:3.6
    container_name: flops_db
    hostname: flops_db
    ports:
      - "10027:10027"
    volumes:
      - 'flops_db:/mongodb'
    command: mongod --port 10027

  mlflow_tracking_server:
    image: mlflow_tracking_server
    build:
      dockerfile: mlflow_tracking_server.Dockerfile
    container_name: mlflow_tracking_server
    hostname: mlflow_tracking_server
    ports:
      - "7027:7027"
    # TODO fix - currently error occurs: 
    #  WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created.
    #  (sqlite3.OperationalError) unable to open database file
    # volumes:
    #   - 'mlflow_backend_store:/mlflow_backend_store.db'

volumes:
  registry_data:
  flops_db:
    driver: local
  #mlflow_backend_store:

# To be able for the root-orchestrator (RO) compose services to reach the flops services
# an easy solution is to place the flops services into the same docker network.
# Otherwise the flops services cannot be reached by the RO services.
# https://stackoverflow.com/a/42114724
networks:
  root_orchestrator_default:
    external: true
