version: "3.3"

services:

  root_fl_manager:
    image: root_fl_manager
    build: .
    hostname: root_fl_manager
    container_name: root_fl_manager
    environment:
      - ROOT_FL_MANAGER_PORT=5072
      - ROOT_FL_IMAGE_REGISTRY_PORT=5073
      - SYSTEM_MANAGER_IP=system_manager
      - SYSTEM_MANAGER_PORT=10000
      - ROOT_FL_MQTT_BROKER_PORT=9027
      - ROOT_FL_MQTT_BROKER_URL=root_fl_mqtt
      - ROOT_FL_MONGO_DB_PORT=10027
      - CAROOT=/etc/ssl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ssl:/etc/ssl
    expose:
      - "5072"
    ports:
      - "5072:5072"
    networks:
      - root_orchestrator_default
  
  root_fl_image_registry:
    image: registry:2.8.3
    container_name: root_fl_image_registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5073
      - REGISTRY_HTTP_TLS_CERTIFICATE=/etc/ssl/registry.pem
      - REGISTRY_HTTP_TLS_KEY=/etc/ssl/registry-key.pem
    volumes:
      - registry_data:/var/lib/registry
      - ssl:/etc/ssl
    expose:
      - "5073"
    ports:
      - "5073:5073"
    depends_on: [root_fl_manager]
    networks:
      - root_orchestrator_default

  root_fl_mqtt:
    image: eclipse-mosquitto:2
    hostname: root_fl_mqtt
    container_name: root_fl_mqtt
    restart: unless-stopped
    ports:
      - "9027:9027"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mosquitto/data
      - /mosquitto/log

  mongo_root_fl:
    image: mongo:3.6
    container_name: mongo_root_fl
    hostname: mongo_root_fl
    ports:
      - "10027:10027"
    volumes:
      - 'mongo_root_fl:/mongodb'
    command: mongod --port 10027

volumes:
  registry_data:
  ssl:
  mongo_root_fl:
    driver: local

# To be able for the root-orchestrator (RO) compose services to reach the root fl services
# an easy solution is to place the fl root services into the same docker network.
# Otherwise the fl root services cannot be reached by the RO services.
# https://stackoverflow.com/a/42114724
networks:
  root_orchestrator_default:
    external: true
