{
    "_id": {"$oid": "65faa3be5e4384d4323947e6"},
    "job_name": "fltest.fl.fl testing.fl",
    "added_files": [],
    "app_name": "fltest",
    "app_ns": "fl",
    "applicationID": "65faa3be411613c70ab7fcd4",
    "bandwidth_in": 0,
    "bandwidth_out": 0,
    "code": "https://github.com/Malyuk-A/mlflower-test-a",
    "image": "https://github.com/Malyuk-A/mlflower-test-a",
    "instance_list": [],
    "memory": 2000,
    "microserviceID": "65faa3be5e4384d4323947e6",
    "microservice_name": "fl testing",
    "microservice_namespace": "fl",
    "next_instance_progressive_number": 0,
    "service_name": "fl testing",
    "service_ns": "fl",
    "state": "",
    "storage": 0,
    "vcpus": 2,
    "vgpus": 0,
    "virtualization": "ml-repo",
    "vtpus": 0,
}
